language: php
dist: bionic

php:
  - 7.3
  - 7.4

services:
  - mysql
    
before_install:
  - mysql --version
  - mysql -e 'CREATE DATABASE foodcoopshop_test;'
  - mysql foodcoopshop_test < ./config/sql/_installation/clean-db-structure.sql
  - mysql foodcoopshop_test < ./tests/config/sql/test-db-data.sql

before_script:
  - phpenv config-rm xdebug.ini
  - php --version
  - composer install --optimize-autoloader
  - cp ./config/travis/* ./config/
  - npm --prefix ./webroot install ./webroot

script:
  - vendor/bin/phpstan analyze -c phpstan.neon --no-interaction --no-progress
  - bash devtools/eslint.sh
  - vendor/bin/phpunit --stderr
  # - sudo cat ./logs/error.log
  
notifications:
  email: false
